export const LOGIN_START = 'LOGIN_START';
export const LOGIN_START_SUCCESS = 'LOGIN_START_SUCCESS';
export const LOGIN_START_FAIL = 'LOGIN_START_FAIL';

export const LOADER_START = 'LOADER_START';
export const LOADER_STOP = 'LOADER_STOP';
